default_platform(:ios)

platform :ios do
  lane :test do
    # Run unit tests
    run_tests(scheme: "uSurfTests")
  end

  lane :TestFlightDeployment do
    # Use the certificate-help repository for Match
    match(
      type: "appstore",
      git_url: "git@github.com:matthewjagiela/certificate-help.git",
      app_identifier: "com.uapps.uSurf",
      username: ENV["APP_STORE_CONNECT_USERNAME"],
      team_id: ENV["APP_STORE_CONNECT_TEAM_ID"],
      api_key: ENV["APP_STORE_CONNECT_API_KEY"]
    )

    # Get version number from Info.plist
    version_number = get_version_number(xcodeproj: "uSurf.xcodeproj")

    # Increment build number
    increment_build_number(xcodeproj: "uSurf.xcodeproj")

    # Build the app for the App Store
    gym(
      scheme: "uSurf",
      export_method: "app-store",
      output_directory: "output",
      output_name: "uSurf.ipa"
    )
    
    upload_to_testflight(
    	api_key: api_key,
    	skip_submission: true,
    	ipa: "output/uSurf.ipa",
    	skip_waiting_for_build_processing: true,
    )
  end
end
