name: CI

on:
  pull_request:
    branches:
      - Develop
      - Release
  push:
    branches:
      - Develop
      - Release

env:
  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout uAppsLibrary
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
        run: |
          ssh-add -D
          ssh-add <(echo "$SSH_PRIVATE_KEY")
          git clone git@github.com:matthewjagiela/uAppsLibrary.git
      - name: Install Bundler
        run: gem install bundler
      - name: Install Dependencies
        run: bundle install
      - name: Run Tests
        run: bundle exec fastlane test

  deploy:
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/release'
    steps:
      - name: Checkout uAppsLibrary
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ env.SSH_PRIVATE_KEY }}
        run: |
          ssh-add -D
          ssh-add <(echo "$SSH_PRIVATE_KEY")
          git clone git@github.com:matthewjagiela/uAppsLibrary.git
      - name: Install Bundler
        run: gem install bundler
      - name: Install Dependencies
        run: bundle install
      - name: Build and Sign
        run: bundle exec fastlane deploy
