name: CI

on:
  pull_request:
    branches:
      - Develop
      - Release
  push:
    branches:
      - Develop
      - Release

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Bundler
        run: gem install bundler
      - name: Install Dependencies
        run: bundle install
      - name: Run Tests
        run: bundle exec fastlane ios run_tests

  deploy:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/release' || github.ref == 'refs/heads/Develop' || github.ref == 'refs/heads/fastlane-self-hosted-API-BN'
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Bundler
        run: gem install bundler
      - name: Install Dependencies
        run: bundle install
      - name: Build and Sign
        run: bundle exec fastlane ios testflight_deployment
        env:
          APP_STORE_CONNECT_API_KEY_ID: ${{secrets.APP_STORE_CONNECT_API_KEY_ID}}
          APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{secrets.APP_STORE_CONNECT_API_KEY_ISSUER_ID}}
          APP_STORE_CONNECT_API_KEY: ${{secrets.APP_STORE_CONNECT_API_KEY}}
          APP_STORE_CONNECT_USERNAME: ${{secrets.APP_STORE_CONNECT_USERNAME}}
          APP_STORE_CONNECT_TEAM_ID: ${{secrets.APP_STORE_CONNECT_TEAM_ID}}
