name: CI

on:
  pull_request:
    branches:
      - Develop
      - Release
  push:
    branches:
      - Develop
      - Release
      - fastlane-self-hosted

jobs:
#   test:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - name: Install Bundler
#         run: gem install bundler
#       - name: Install Dependencies
#         run: bundle install
#       - name: Run Tests
#         run: bundle exec fastlane test

  deploy:
    runs-on: self-hosted
#     needs: test
    if: github.ref == 'refs/heads/fastlane-self-hosted' || github.ref == 'refs/heads/release'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Bundler
        run: gem install bundler
      - name: Show Variable
        run: echo "$APP_STORE_CONNECT_API_KEY"
      - name: Install Dependencies
        run: bundle install
      - name: Build and Sign
        run: bundle exec fastlane TestFlightDeployment
