name: CI

on:
  pull_request:
    branches:
      - Develop
  push:
    branches:
      - Develop

jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Bundler
        run: gem install bundler
      - name: Install Dependencies
        run: bundle install
      - name: Run Tests
        run: bundle exec fastlane test

  deploy:
    runs-on: macos-latest
    needs: test
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Bundler
        run: gem install bundler
      - name: Install Dependencies
        run: bundle install
      - name: Build and Sign
        run: bundle exec fastlane deploy
      - name: Upload to App Store
        uses: jenkinsci/upload-to-app-store@3.0
        with:
          api_key: ${{ secrets.APP_STORE_CONNECT_API_KEY }}
          issuer_id: ${{ secrets.APP_STORE_CONNECT_ISSUER_ID }}
          id: ${{ secrets.APP_STORE_CONNECT_APP_ID }}
          ipa_path: "./uSurf.ipa"
          app_name: "uSurf"
