name: CI - Test

on:
  pull_request:
    branches:
      - Develop
      - Release

jobs:
  Unit-Test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Bundler
        run: gem install bundler
      - name: Install Dependencies
        run: bundle install
      - name: Run Tests
        run: bundle exec fastlane ios test
